"""
layout.py -- write the generated code as a buildable source tree.

One 100 MB translation unit is hostile to work with: a single compiler crash
or interruption loses everything, and nothing rebuilds incrementally.  So the
output is a tree instead:

    include/guest_rt.h      runtime (copied)
            guest_config.h  generated: guest state layout
            guest_decls.h   generated: every declaration + inline helpers
            guest_api.h     generated: the exported entry points
    src/data_ro.c           read-only image        -- one array
        data_rw.c           writable image         -- one array
        data_text.c         code-as-data image     -- only if referenced
        relocate.c          pointer relocation
        thunks.c            imported-symbol thunks
        entries.c           exported entry points
        fn/f_<addr>.c       one file per translated function
    Makefile

Each function compiles independently, so a build resumes where it stopped and
runs in parallel.
"""

import os
import re
import shutil
import sys


MAKEFILE = r'''# Generated by elf2c.
#
# Every function is its own object file, so an interrupted build resumes and
# `make -j` scales.  Implicit declarations are an ERROR here on purpose: an
# import without a prototype is silently treated as int-returning, which
# truncates 64-bit pointers and produces a crash far from the real cause.

CC      ?= cc
AR      ?= ar

# Command echo.  This tree is ~56,000 objects, and the default make behaviour
# prints the whole `cc -std=c11 -fno-strict-aliasing -Werror=... -march=... -MMD
# -MP -c src/fn/f_00a003a8.c -o build/src/fn/f_00a003a8.o` line for every one of
# them.  A warning in that scroll is invisible, which is the opposite of what
# -Werror=implicit-function-declaration is here for.  So the recipes print one
# short line per file and the command itself is silenced:
#
#     make            ->   CC  src/fn/f_00a003a8.c
#     make V=1        ->   the full command lines, as before
#
# V=1 is what to use when a compile fails and the exact flags matter.
V ?= 0
ifeq ($(V),0)
Q := @
else
Q :=
endif
# -g on ~15,000 objects costs several GB.  Off by default; turn it on with
# `make DEBUG=1` when a crash needs addr2line.
DEBUG   ?= 0
ifeq ($(DEBUG),1)
CFLAGS  ?= -O1 -g
else
CFLAGS  ?= -O1 -g0
endif
CPPFLAGS += -Iinclude

# The read-only image is a binary blob, not C source: data_ro.c pulls it in
# with C23 `#embed`, whose path is relative to data_ro.c itself, so there is
# nothing for the Makefile to pass.  This needs GCC 15+ or clang 19+.

# -march=x86-64-v3 rather than -mavx2.  v3 IS AVX2 plus BMI1/BMI2, FMA,
# LZCNT/TZCNT and F16C, and the one that pays for itself is FMA: the fused
# multiply-add helpers of section 24.6 call C99 `fma`/`fmaf`, and without the
# FMA instruction that is a LIBM CALL on every fused multiply-add the guest
# performs.  With v3 it is a single `vfmadd`.  Measured on a translated
# function that uses it: `call fma` -> `vfmadd`, and the generated code is the
# same size to within 0.2% (150-file sample, section 28).
#
# It requires Haswell (2013) or later.  Drop to `-mavx2` for an older host;
# nothing else in the tree depends on v3.
#
# (`-mavx2` alone did work, despite the driver putting its default
# `-march=x86-64` AFTER it on the cc1 command line -- GCC records explicitly
# requested ISA bits and -march does not clear them.  Checked, because the
# ordering makes it look as though it would.)
CFLAGS  += -std=c11 -fno-strict-aliasing -Werror=implicit-function-declaration -march=x86-64-v3
# Hook for one-off experiments (e.g. `make EXTRA_CFLAGS=-flto=auto`).  A
# command-line CFLAGS= would REPLACE the line above, dropping -std=c11 and
# -march= and failing for reasons that have nothing to do with the experiment.
CFLAGS  += $(EXTRA_CFLAGS)
LDLIBS  += -lpthread -lm
# Windows needs dbghelp for the backtrace helper in guest_rt.c.  guest_rt.c
# asks for it with `#pragma comment(lib, "dbghelp.lib")`, which MSVC honours
# and GCC IGNORES SILENTLY -- so a MinGW link fails on SymInitialize with
# nothing to say where the requirement came from.  The test covers both ways of
# reaching a Windows target: building ON Windows (OS is set) and CROSS-building
# with a mingw toolchain (the compiler's name is the only signal there).
ifeq ($(OS),Windows_NT)
LDLIBS  += -ldbghelp
else ifneq ($(findstring mingw,$(CC)),)
LDLIBS  += -ldbghelp
endif
# No -lstdc++: the two C++ allocation operators the guest imports go through
# guest_operator_new/guest_operator_delete in guest_host.c, because their
# mangled names differ per ABI and do not resolve on Windows (HANDOVER 15).

# -no-pie is for SIZE, not correctness.  A plain PIE link is equally correct
# (all 10 shaders byte-identical), but it needs a 24-byte dynamic relocation
# for each of the ~835,000 pointers in the image -- 20 MB of .rela.dyn, 90.7 MB
# of binary against 70.6 MB, and the loader applies them all at startup.
# -Wl,-Ttext-segment is NOT here: it guarded a constraint that does not exist
# (the original ELF targets a 64-bit address space).  HANDOVER sections 3.4, 18.
LDFLAGS += -no-pie

# Define this to build without the project's own glslc_Alloc/Free/Realloc.
CPPFLAGS += -DGUEST_PROVIDE_GLSLC_ALLOC

# Overridable so that a second toolchain can build into its own directory
# without discarding the first one's objects:
#     make BUILD_DIR=build-win CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar
BUILD_DIR ?= build

SRCS := $(wildcard src/*.c) $(wildcard src/fn/*.c) $(wildcard runtime/*.c)
# Map source files to the build directory
OBJS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(SRCS))
DEPS := $(OBJS:.o=.d)

# OS-aware directory management and cleanup commands
ifeq ($(OS),Windows_NT)
MKDIR_P = if not exist "$(subst /,\,$(@D))" mkdir "$(subst /,\,$(@D))"
RM_DIR_CMD = if exist "$(BUILD_DIR)" rmdir /S /Q "$(BUILD_DIR)"
RM_FILE = if exist "$(@)" del /Q /F "$(subst /,\,$@)"
RM_LIB_TMP = if exist "$(subst /,\,$(LIB_TMP))" del /Q /F "$(subst /,\,$(LIB_TMP))"
MV_LIB_TMP = move /Y "$(subst /,\,$(LIB_TMP))" "$(subst /,\,$(LIB))" >nul
else
MKDIR_P = mkdir -p $(@D)
RM_DIR_CMD = rm -rf $(BUILD_DIR)
RM_FILE = rm -f $@
RM_LIB_TMP = rm -f $(LIB_TMP)
MV_LIB_TMP = mv -f $(LIB_TMP) $(LIB)
endif

# CFG recovery occasionally glues a large stretch of code into a single "function"
BIG_THRESHOLD ?= 4000000
ifeq ($(OS),Windows_NT)
# make often runs $(shell) via a temp .bat file on Windows, requiring %% for loop variables
RAW_BIG_SRCS := $(shell cmd /c "for %%I in (src\fn\*.c) do @if %%~zI GTR $(BIG_THRESHOLD) echo %%I")
BIG_SRCS := $(subst \,/,$(RAW_BIG_SRCS))
else
BIG_SRCS := $(shell find src/fn -name '*.c' -size +$(shell expr $(BIG_THRESHOLD) / 1024)k 2>/dev/null)
endif
BIG_OBJS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(BIG_SRCS))

LIB := $(BUILD_DIR)/libguest.a
LIB_TMP := $(BUILD_DIR)/libguest.a.tmp
OBJS_RSP := $(BUILD_DIR)/objs.rsp

# The command-line front end.  tools/glslc_cli.c is copied into the tree beside
# the library it drives (layout.py), so `make cli` works in a tree that was
# handed over on its own -- which is what the previous instructions assumed and
# nothing actually did.
CLI_SRC := tools/glslc_cli.c
CLI     := $(BUILD_DIR)/glslc

.PHONY: all clean test cli
all: $(LIB)

# The archive is built under a TEMPORARY NAME and renamed into place, because
# `ar` over 56,000 objects takes minutes and an interrupted run leaves an
# 8-byte stub behind -- newer than every object, so the next `make` considers it
# up to date and every link then fails with "undefined reference to
# glslcCompile".  Renaming makes the archive appear only when it is complete.
$(LIB): $(OBJS)
	@$(MKDIR_P)
	@echo AR  $@ -- $(words $(OBJS)) objects
	$(file >$(OBJS_RSP),$(OBJS))
	@$(RM_LIB_TMP)
	$(Q)$(AR) rcs $(LIB_TMP) @$(OBJS_RSP)
	$(Q)$(MV_LIB_TMP)
	@echo built $@ from $(words $(OBJS)) objects

# Pattern rule for oversized objects
$(BIG_OBJS): $(BUILD_DIR)/%.o: %.c
	@$(MKDIR_P)
	@echo CC  $< -- oversized, building at -O0
	$(Q)$(CC) $(CPPFLAGS) -std=c11 -fno-strict-aliasing -march=x86-64-v3 -O0 $(EXTRA_CFLAGS) -MMD -MP -c $< -o $@

# Standard pattern rule mapped to build directory
$(BUILD_DIR)/%.o: %.c
	@$(MKDIR_P)
	@echo CC  $<
	$(Q)$(CC) $(CPPFLAGS) $(CFLAGS) -MMD -MP -c $< -o $@

# `#embed` is not visible to -MMD, so the dependency on the image has to be
# stated: without it a regenerated image would not rebuild.
$(BUILD_DIR)/src/data_ro.o: src/data_ro.bin

# `make cli` -- build the front end and link it against the library.  This is
# the ONLY thing needed to get a working compiler out of a generated tree:
#
#     make -r -j$(nproc)     # the library, ~40-55 minutes
#     make cli               # seconds
#     ./build/glslc --help
#
# -no-pie comes from LDFLAGS (it is for size, HANDOVER sec.18) and -rdynamic
# makes the runtime's own backtrace helper able to name functions.
cli: $(CLI)

$(CLI): $(CLI_SRC) $(LIB)
	@$(MKDIR_P)
	@echo CC  $(CLI_SRC)
	$(Q)$(CC) $(CPPFLAGS) $(CFLAGS) -c $(CLI_SRC) -o $(BUILD_DIR)/glslc_cli.o
	@echo LD  $@
	$(Q)$(CC) $(CFLAGS) $(LDFLAGS) -rdynamic -o $@ $(BUILD_DIR)/glslc_cli.o $(LIB) $(LDLIBS)

# `make test` needs tests/test_entry.c, which is NOT part of a generated tree --
# it lives in the package.  Point the target at wherever it is rather than
# failing with a missing-object message that says nothing:
#     make test TEST_ENTRY=/path/to/glslcport/tests/test_entry.c
TEST_ENTRY ?= tests/test_entry.c

test: $(LIB)
	@$(MKDIR_P)
	@echo CC  $(TEST_ENTRY)
	$(Q)$(CC) $(CPPFLAGS) $(CFLAGS) -c $(TEST_ENTRY) -o $(BUILD_DIR)/test_entry.o
	@echo LD  $(BUILD_DIR)/testrun
	$(Q)$(CC) $(CFLAGS) $(LDFLAGS) -o $(BUILD_DIR)/testrun $(BUILD_DIR)/test_entry.o $(LIB) $(LDLIBS)

clean:
	@$(RM_DIR_CMD)

-include $(DEPS)
'''


def _write(path, lines):
    """Write only when the content actually changes.

    Regenerating rewrites every file; if the bytes are identical, leaving the
    timestamp alone is what keeps `make` incremental after a small fix.
    """
    data = '\n'.join(lines) + '\n'
    try:
        with open(path, 'r') as fh:
            if fh.read() == data:
                return False
    except (IOError, OSError):
        pass
    with open(path, 'w') as fh:
        fh.write(data)
    return True


class FunctionWriter(object):
    """Writes per-function files as they are produced.

    Holding every function's C text in memory until the end costs several GB on
    a binary this size -- enough to get the generator OOM-killed.  Each file is
    independent, so it can go to disk immediately and only its name needs to be
    remembered (for pruning stale files at the end).
    """

    def __init__(self, outdir):
        self.fn_dir = os.path.join(outdir, 'src', 'fn')
        os.makedirs(self.fn_dir, exist_ok=True)
        self.written = set()
        # Distinct FILES whose content changed on disk, not write() calls.
        # A folded function is written twice -- once with its body in pass 2,
        # then again as a stub -- so counting calls double-counted it and could
        # report more "files" than the tree contains.  _write() only touches a
        # file when the content actually differs, so this set is exactly the
        # set make will rebuild.
        self.changed_files = set()
        self.write_calls = 0
        # Per-file headers instead of one shared 1.9 MB guest_decls.h.
        # That header was included by all 43,633 files -- about 86 GB of header
        # text parsed for ~3 KB of real content each.  Each file now declares
        # only what it actually references.
        self.header = ['#include "guest_core.h"', '']
        self.deps = {}          # addr -> names this file references
        self.decl_for = {}      # name -> its declaration

    def unwrite(self, addr):
        """Remove a function file that should never have existed.

        A block that some other function claims as an interior block must not
        also have a standalone translation -- entering it directly would skip
        the owner's prologue and still run its epilogue (HANDOVER.md sec.21).
        Serial emission never writes one because the claim is made before the
        loop reaches that address; parallel emission can dispatch it first and
        learn afterwards.  Enforcing the rule at the END makes the result the
        same either way, instead of depending on the order functions were
        emitted in.
        """
        name = 'f_%08x.c' % addr
        if name not in self.written:
            return False
        try:
            os.remove(os.path.join(self.fn_dir, name))
        except OSError:
            pass
        self.written.discard(name)
        self.changed_files.discard(name)
        return True

    def write(self, addr, lines, deps=None):
        name = 'f_%08x.c' % addr
        self.written.add(name)
        head = list(self.header)
        if deps:
            decls = sorted(self.decl_for[d] for d in deps if d in self.decl_for)
            if decls:
                head = head[:1] + [''] + decls + ['']
        self.write_calls += 1
        if _write(os.path.join(self.fn_dir, name), head + lines):
            self.changed_files.add(name)
        else:
            # An identical rewrite leaves the file alone, so a file changed by
            # an earlier pass and restored by a later one is correctly absent
            # from changed_files -- make would not rebuild it either.
            self.changed_files.discard(name)

    def prune_unreachable(self, outdir):
        """Delete function files that nothing can ever reach.

        The generator emits a standalone translation for every jump-table arm
        whose owner it could not determine ("orphan jump-table arms translated
        standalone").  When an owner DOES exist and already emits that address
        as one of its blocks, the standalone copy is unreachable: the dispatch
        table names the owner, so nothing ever calls it.  Measured on this
        binary, 26,125 of 43,624 function files -- 60%, 20.4 MB of C -- were in
        that state, and each one had re-walked its owner's tail, which is where
        77.7 MB of duplicated block text came from (two "functions" 4 bytes
        apart both emitting the same 629 blocks).

        The linker already discards them: linking the archive rather than the
        object files produced a binary 4.37 MB smaller and 4.6x faster to link.
        So this changes nothing about the result -- it just stops generating
        and compiling ~26,000 files first.

        Reachability is computed exactly the way the linker computes it.  Roots
        are the functions named by the aggregate files (the dispatch table, the
        exported entry points, the writable image's vtables and the import
        thunks); the graph is each file's own declaration list, which the
        writer emits for precisely the names that file references.
        """
        src = os.path.join(outdir, 'src')
        ref = re.compile(r'\bf_([0-9a-f]{8,})\b')

        roots = set()
        for name in ('dispatch.c', 'entries.c', 'thunks.c', 'data_rw.c',
                     'data_text.c'):
            path = os.path.join(src, name)
            try:
                with open(path) as fh:
                    roots.update(ref.findall(fh.read()))
            except (IOError, OSError):
                pass

        # Adjacency straight from the files, so it cannot drift from what was
        # actually written.
        deps = {}
        for fname in os.listdir(self.fn_dir):
            if not fname.endswith('.c'):
                continue
            key = fname[2:-2]
            with open(os.path.join(self.fn_dir, fname)) as fh:
                names = set()
                for line in fh:
                    if line.startswith('void f_'):
                        # 'void f_71000111dc(cpu_t *...' -> '71000111dc', the
                        # same key the file names use.  Slicing one character
                        # short here silently produced an empty graph: every
                        # edge missed, so the closure kept only the roots and
                        # pruned 26,125 files that ARE called.
                        names.add(line[len('void f_'):].split('(')[0])
                    elif line.startswith('L_') or line.startswith('    '):
                        break          # declarations are all at the top
            deps[key] = names

        live, work = set(), [r for r in roots if r in deps]
        while work:
            a = work.pop()
            if a in live:
                continue
            live.add(a)
            work.extend(d for d in deps.get(a, ()) if d not in live)

        removed = 0
        for key in deps:
            if key in live:
                continue
            for ext in ('.c', '.o', '.d'):
                path = os.path.join(self.fn_dir, 'f_' + key + ext)
                if os.path.exists(path):
                    os.remove(path)
            self.written.discard('f_%s.c' % key)
            self.changed_files.discard('f_%s.c' % key)
            removed += 1
        return removed

    def prune(self):
        stale = 0
        for name in os.listdir(self.fn_dir):
            if name.endswith('.c') and name not in self.written:
                os.remove(os.path.join(self.fn_dir, name))
                for ext in ('.o', '.d'):
                    extra = os.path.join(self.fn_dir, name[:-2] + ext)
                    if os.path.exists(extra):
                        os.remove(extra)
                stale += 1
        return stale


def write_tree(ctx, outdir, runtime_dir, pieces):
    """pieces: dict with keys config, decls, api, ro, rw, text, relocate,
    thunks, entries, functions (addr -> list of lines)."""
    inc = os.path.join(outdir, 'include')
    src = os.path.join(outdir, 'src')
    fn = os.path.join(src, 'fn')
    rt = os.path.join(outdir, 'runtime')
    for d in (inc, src, fn, rt):
        os.makedirs(d, exist_ok=True)

    # Runtime files are copied only when their CONTENT differs.  shutil.copy
    # updates the mtime unconditionally, and since every generated object
    # depends on guest_rt.h, an unchanged copy would still force a full
    # rebuild of every function -- about an hour here for no reason.
    def copy_if_changed(src_path, dst_path):
        try:
            with open(src_path, 'rb') as a, open(dst_path, 'rb') as b:
                if a.read() == b.read():
                    return False
        except (IOError, OSError):
            pass
        shutil.copy(src_path, dst_path)
        return True

    copied = 0
    for name in ('guest_rt.h',):
        copied += copy_if_changed(os.path.join(runtime_dir, name),
                                  os.path.join(inc, name))
    # guest_eh.c and guest_cxx.c are always copied, even for a binary with no
    # exceptions: their generated hooks are weak-defaulted, so they cost that
    # binary two small objects and nothing else, and keeping the runtime set
    # fixed means a tree does not need to know which input it came from.
    for name in ('guest_rt.c', 'guest_host.c', 'guest_va.c', 'guest_scanf.c',
                 'guest_printf.c', 'guest_wide.c',
                 'guest_eh.c', 'guest_cxx.c', 'guest_va_int.h'):
        copied += copy_if_changed(os.path.join(runtime_dir, name),
                                  os.path.join(rt, name))
    # runtime/musl/ holds musl's own conversion code, vendored (guest_scanf.c
    # explains why).  It is a DIRECTORY of files that are #included rather than
    # compiled on their own -- the Makefile's `runtime/*.c` wildcard must not
    # pick them up, which is exactly why they live one level down.
    mrt = os.path.join(rt, 'musl')
    os.makedirs(mrt, exist_ok=True)
    msrc = os.path.join(runtime_dir, 'musl')
    if os.path.isdir(msrc):
        for name in sorted(os.listdir(msrc)):
            if name.endswith(('.c', '.h')):
                copied += copy_if_changed(os.path.join(msrc, name),
                                          os.path.join(mrt, name))

    # glslcinterface.h is the INTEGRATOR's header, not the generator's, and
    # entries.c includes it -- so a tree generated without it does not compile,
    # which is a confusing first error for something the operator already has.
    # When a copy sits beside the package it is copied in; when it does not,
    # the message says exactly what to do (HANDOVER sec.3.2 says the same, but
    # at the point of failure is where it gets read).
    pkg_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # tools/glslc_cli.c: the front end, copied in so that `make cli` works in a
    # tree on its own.  It is the integrator-facing program, not generated
    # output, which is why it lives beside the tree rather than in src/.
    cli_src = os.path.join(pkg_root, 'tools', 'glslc_cli.c')
    if os.path.isfile(cli_src):
        os.makedirs(os.path.join(outdir, 'tools'), exist_ok=True)
        copied += copy_if_changed(cli_src, os.path.join(outdir, 'tools', 'glslc_cli.c'))

    iface = os.path.join(pkg_root, 'glslcinterface.h')
    if os.path.isfile(iface):
        copied += copy_if_changed(iface, os.path.join(inc, 'glslcinterface.h'))
    elif not os.path.isfile(os.path.join(inc, 'glslcinterface.h')):
        sys.stderr.write(
            'note: glslcinterface.h not found beside the package; copy your '
            'own into %s before building (src/entries.c includes it)\n' % inc)

    _write(os.path.join(inc, 'guest_config.h'), pieces['config'])
    _write(os.path.join(inc, 'guest_decls.h'), pieces['decls'])
    # The slim header for the ~43,000 per-function files.
    _write(os.path.join(inc, 'guest_core.h'),
           ['/* Minimal shared header: runtime, images, dispatch, helpers.',
            ' * Per-function declarations live in the files that use them,',
            ' * because including them all here cost ~86 GB of parsing across',
            ' * the tree. */',
            '#ifndef GUEST_CORE_H',
            '#define GUEST_CORE_H',
            '#include "guest_decls.h"',
            '#endif'])
    _write(os.path.join(inc, 'guest_api.h'), pieces['api'])

    if pieces.get('aggregate_decls'):
        _write(os.path.join(inc, 'guest_all.h'), pieces['aggregate_decls'])
    # The aggregate files reference thousands of functions each, so they -- and
    # only they -- include the full declaration list.
    hdr = ['#include "guest_all.h"', '']

    # The read-only image as raw bytes beside its .c file.  Written only when
    # the content differs, like everything else here, so an unchanged image
    # does not restamp the file and force data_ro.o to rebuild.
    ro_bin = os.path.join(src, 'data_ro.bin')
    blob = pieces.get('ro_blob')
    if blob is not None:
        try:
            with open(ro_bin, 'rb') as fh:
                same = fh.read() == blob
        except (IOError, OSError):
            same = False
        if not same:
            with open(ro_bin, 'wb') as fh:
                fh.write(blob)

    # data_ro.c needs nothing but the g_ro declaration, so it takes the slim
    # header.  data_rw.c is the opposite: its initialisers name thousands of
    # functions and every import thunk, so it needs the full list -- it is now
    # one of the files that reads guest_all.h, in place of relocate.c.
    _write(os.path.join(src, 'data_ro.c'),
           ['#include "guest_core.h"', ''] + pieces['ro'])
    _write(os.path.join(src, 'data_rw.c'), hdr + pieces['rw'])
    text_path = os.path.join(src, 'data_text.c')
    if pieces.get('text'):
        _write(text_path, hdr + pieces['text'])
    elif os.path.exists(text_path):
        # No longer needed: code addresses are emitted as plain constants, so
        # nothing references a data copy of .text.  Left behind it would still
        # be picked up by the wildcard and compiled into the library.
        os.remove(text_path)
        for ext in ('.o', '.d'):
            extra = os.path.join(src, 'data_text' + ext)
            if os.path.exists(extra):
                os.remove(extra)
    _write(os.path.join(src, 'helpers.c'), hdr + pieces.get('helpers', []))

    # Was relocate.c, which held guest_relocate() plus the dispatch table.
    # Relocation is the linker's job now, so only the dispatch table is left
    # and the old name would be a lie.  It still needs guest_all.h: the table
    # names every translated function.
    _write(os.path.join(src, 'dispatch.c'), hdr + pieces['dispatch'])
    for stale in ('relocate.c', 'relocate.o', 'relocate.d'):
        stale_path = os.path.join(src, stale)
        if os.path.exists(stale_path):
            os.remove(stale_path)
    _write(os.path.join(src, 'thunks.c'), hdr + pieces['thunks'])
    _write(os.path.join(src, 'entries.c'),
           ['#include "guest_all.h"', '#include "guest_api.h"', ''] + pieces['entries'])

    stale = pieces.get('pruned', 0)

    with open(os.path.join(outdir, 'Makefile'), 'w') as fh:
        fh.write(MAKEFILE)

    return {
        'functions': pieces.get('function_count', 0),
        'pruned': stale,
        'files': 7 + pieces.get('function_count', 0) + (1 if pieces.get('text') else 0),
    }
